// Mocks generated by Mockito 5.4.6 from annotations
// in jobboardhrapp/test/features/auth/presentation/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fpdart/fpdart.dart' as _i5;
import 'package:jobboardhrapp/core/error/failures.dart' as _i6;
import 'package:jobboardhrapp/core/usecase/use_case.dart' as _i11;
import 'package:jobboardhrapp/features/auth/data/models/company_model.dart'
    as _i7;
import 'package:jobboardhrapp/features/auth/domain/auth_repository.dart' as _i2;
import 'package:jobboardhrapp/features/auth/domain/usecases/company_login.dart'
    as _i3;
import 'package:jobboardhrapp/features/auth/domain/usecases/company_signup.dart'
    as _i9;
import 'package:jobboardhrapp/features/auth/domain/usecases/is_user_logged_in.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CompanyLogInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompanyLogInUseCase extends _i1.Mock
    implements _i3.CompanyLogInUseCase {
  MockCompanyLogInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.CompanyModel>> call(
    _i3.CompanyLogInParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, _i7.CompanyModel>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, _i7.CompanyModel>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.CompanyModel>>);
}

/// A class which mocks [CompanySignUpUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompanySignUpUsecase extends _i1.Mock
    implements _i9.CompanySignUpUsecase {
  MockCompanySignUpUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.CompanyModel>> call(
    _i9.CompanySignUpParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, _i7.CompanyModel>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, _i7.CompanyModel>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.CompanyModel>>);
}

/// A class which mocks [IsUserLoggedIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsUserLoggedIn extends _i1.Mock implements _i10.IsUserLoggedIn {
  MockIsUserLoggedIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Either<_i6.Failure, bool>> call(_i11.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, bool>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, bool>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, bool>>);
}
